### ISSUE TITLE
Class name not documented anywhere

### ISSUE THREAD

**Issue by tomchambers2** [shiffman/Box2D-for-Processing#15]
I've been reading The Nature of Code and in there the class name is `PBox2D`. Since the readme refers to that for documentation, it took a while to find that the new class name is `Box2DProcessing`. It would be useful if this were noted in the readme/book.

**Comment by shiffman** [comment]
Indeed, this fixed for Nature of Code 2 which I am *finally* actively working on getting on the website and in print!  https://github.com/shiffman/The-Nature-of-Code/pull/21
